language: scala
scala:
- 2.12.7
script:
- sbt test
deploy:
- provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && echo 'version in ThisBuild := "$TRAVIS_TAG"' > version.sbt && sbt publish
  on:
    branch: master
    tags: true
