---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: optimization
spec:
  clusterResourceWhitelist:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  sourceRepos:
    - https://github.com/conorfennell/example-app.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: default
  description: "Applications that are used as an example app"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
spec:
  project: optimization
  source:
    repoURL: https://github.com/conorfennell/example-app.git
    path: chart
    componentParameterOverrides:
      - name: resources.requests.cpu
        value: 100m
  destination:
    server: https://kubernetes.default.svc
    namespace: default
